### ISSUE TITLE
Total in Donut/Pie chart behind chart's svg

### ISSUE THREAD

**Issue by cnavarreteliz** [d3plus/d3plus-hierarchy#37]
Hi, I was working with total in d3plus, and when I tried to use in Donut/Pie charts I found a weird behaviour, because total title was positioned behind chart's svg.

[https://jsfiddle.net/gwcxts4n/](https://jsfiddle.net/gwcxts4n/)

![image](https://user-images.githubusercontent.com/5233593/40140657-78286bf8-5921-11e8-98f6-327737f00a82.png)

**Comment by davelandry** [comment]
fixed in this commit: https://github.com/d3plus/d3plus-hierarchy/commit/021fbcbcd548112539c4516b246c97fd225c8706
