### ISSUE TITLE
show share percentages and values in tooltips by default

### ISSUE THREAD

**Issue by davelandry** [d3plus/d3plus-hierarchy#46]

**Comment by pachadotdev** [comment]
Hi @davelandry 
I was trying to mimic tooltips from version 1. How would you include the share without passing the sum object (i.e. not like this https://jsfiddle.net/0y9ku3vz/1/)?
I checked the source and here is my sketch:
```
function(d) {
        var table = "<table class=\'tooltip-table\'>";
        table += "<tr><td class=\'title\'>Value:</td><td class=\'data\'>" +  d.value + "</td></tr>";
        table += "<tr><td class=\'title\'>Share:</td><td class=\'data\'>" +  Math.round((d.value / d.total) * 100) + "%" + "</td></tr>";
        table += "</table>";
        
        return table;
    }
```

**Comment by davelandry** [comment]
@pachamaltese @cnavarreteliz this feature had been added in v0.8.5. We are showing only the share percentage by default, as there is no way to know how to format the user's raw value (ie. could be dollars, could be weight, etc).

Each accessor function is provided 3 variables:
1. the user's untouched data object
2. the index of that data object in the user's data array
3. the internal d3plus element containing calculated measures

The default behavior uses the `tbody` property of the tooltip like so:

```js
tbody: [
  ["Share", (d, i, x) => `${formatAbbreviate(x.share * 100, this._locale)}%`]
]
```

**Comment by pachadotdev** [comment]
@davelandry sounds good, my opinion is that d3plus 1 was amazing
if I had time I'd update its dependencies and prevent it from dying
