### ISSUE TITLE
less agressive highlighting in treemaps

### ISSUE THREAD

**Issue by pachadotdev** [d3plus/d3plus-hierarchy#51]
@davelandry 

as in d3plus 2.0.0 alpha 17, the highlight is much more aggressive with respect to d3plus 1.9.8

for example: https://bl.ocks.org/pachamaltese/c140bebe38e580478a2c0c52b47ee40f

![image](https://user-images.githubusercontent.com/10091065/52660732-12d45200-2edf-11e9-9db9-c2a2f7e3ce95.png)

doesn't look like in the previous version

see for example this: https://bl.ocks.org/pachamaltese/d1014dfc199532284cbb4d75460101be

how can I make the highlighting darker?

**Comment by davelandry** [comment]
Copying response from: https://github.com/alexandersimoes/d3plus/issues/675

You're looking for the [hoverOpacity](http://d3plus.org/docs/#Shape.hoverOpacity) property:

```js
.shapeConfig({
  hoverOpacity: 1
})
```
