### ISSUE TITLE
dynamic depth in TreeMap

### ISSUE THREAD

**Issue by nalhadad** [d3plus/d3plus-hierarchy#65]
Hello,
I used d3plus v1 to create a treeMap where I can change the depth dynamically through a drop down list below the treemap (.ui<value>) like the following example:

<meta charset="utf-8">
<script src="//d3plus.org/js/d3.js"></script>
<script src="//d3plus.org/js/d3plus.js"></script>
<div id="viz"></div>
var sample_data = [
    {"value": 100, "name": "alpha","category":"A", "weight": 80},
    {"value": 70, "name": "beta","category":"A", "weight": 43},
    {"value": 40, "name": "gamma","category":"A", "weight": 64},
    {"value": 15, "name": "delta","category":"B", "weight": 20},
    {"value": 5, "name": "epsilon","category":"A", "weight": 92},
    {"value": 1, "name": "zeta","category":"B", "weight": 35}
  ];

  var visualization = d3plus.viz()
    .container("#viz")
    .data(sample_data)
    .type("tree_map")
    .id(["category","name"])
    .color("category")
    .size("value")
    .ui([
      {
        "method" : "depth",
        "type": "drop",
        "value":[{"category":0},{"name":1}]
      }
    ])
    .draw();

https://jsfiddle.net/f670s3co/

I even use the same logic to change dynamically the color, size and even type (treemap, pie bubble)
I'm passing now to d3plus v2 but I can't reproduce the same behaviour , Can we do the same in version 2? what is equivalant to ".ui" and how do we use it?
Thank you

**Comment by davelandry** [comment]
@nalhadad the new method in v2 is called "controls". The biggest change is needing to pass explicit click events to "on":

```js
.controls([
  {
    options: [
      {text: "Category", value: 0},
      {text: "Name", value: 1}
    ],
    type: "Select",
    on: {
      change: function(d) {
          this.depth(parseInt(d)).render();
      }
    }
  }
])
```
Keys correspond to the methods in d3plus-form: https://github.com/d3plus/d3plus-form

**Comment by nalhadad** [comment]
OK, thank you very much. I'll give it a try
