### ISSUE TITLE
Treemap Combining Groups

### ISSUE THREAD

**Issue by mhealey** [d3plus/d3plus-hierarchy#75]
Expected Behaviour:
-  Treemap combines id's into it's parents.  Each parent is separate from one another.
-  Hex color assignment are easily applied as per tutorials.

Current Map
-  Executing treemap results in combining of several parents
- Hex color's are not assigned

### Steps to Reproduce (for bugs)
Example Data
```js
var data = [
        { parent: "Animal Products",
            id: "Horses",
            value: 27237745.0,
            color: "#F2AA86",
            image: "/images/icons/hs/hs_1.svg",
        },
        { parent: "Animal Products",
            id: "Horses",
            value: 27237745.0,
            color: "#F2AA86",
            image: "/images/icons/hs/hs_1.svg",
        },
.....]
```

Code as it exists:
```js
function currency(x){
        if (x >= 1e9){
          return "$" + (x/1e9).toFixed(2).toString() + " Billion (USD)";
        } else if ( x < 1e9 && x >= 1e6 ){
          return "$" + (x/1e6).toFixed(2).toString() + " Million USD";
        } else {
          return "$" + (x).toFixed(2).toString() + " (USD)";
        }
      }
      new d3plus.Treemap()
        .data(data)
        .config({
          threshold: 0.0,
        })
        .tooltipConfig({
          body: function(d){
            var table = "<table class='tooltip-table'>";
            table+="<tr><td class='title'>Section:</td><td class='data'>" + d.parent + "</td></tr>";
            table+="<tr><td class='title'>HS4:</td><td class='data'>" + d.id + "</td></tr>";
            table+="<tr><td class='title'>AB Exports:</td><td class='data'>" + currency(d.value) + "</td></tr>";
            table+="</table>";
            return table;
          }
        })
        .groupBy(["parent","id"])
        .legend(true)
        .legendConfig({
          shapeConfig: {
            opacity: 0,
            fill: function(d) { console.log(d.color); return d.color; },
            width: 30,
            height: 30,
            backgroundImage: function(d) {
              if (d.image.length == 2) {
                return d.image.slice(-1)[0]
              } else {
                return d.image;
              }
            },
          },
          label: false
        })
        .sum("value")
        .select("#treemap")
        .render();
```

### Your Environment

* Browser Name:  Chrome
* Operating System and Version:  Win 10

**Comment by davelandry** [comment]
@mhealey looking at your setup, the thing that stands out the most to me is that you will probably want to move the `fill` method our from the legend's `shapeConfig`, and into the top level `shapeConfig` that all shapes share. Check out this jsfiddle: https://jsfiddle.net/zjvgcn03/6/

Other than that, I'm not sure what the other problem is. Your data array is 2 identical data points, with the same parent and id, so they get grouped together as being the same entity (and the value is summed). What is your expected behavior here?

**Comment by mhealey** [comment]
I only placed the structure of the example.  In the output, it combines two groups eg

Group 1 example:
{ parent: "Arts and Antiques",
            id: "Paintings",
            value: 4214824.0,
            color: "#847290",
            image: "../images/icons/hs/hs_21.svg",
}

and Group 2 example:
        { parent: "Vegetable Products",
            id: "Other Live Plants",
            value: 244538.0,
            color: "#F4CE0F",
            image: "../images/icons/hs/hs_2.svg",
        }

which have different parents, ids, colors and images.  And the legend shows up as a combination of these two parents, instead of separate representations for each parents.

One of the errors I get is:

hs_20.svg:1 GET http://localhost:8000/images/icons/hs/hs_1.svg,../images/icons/hs/hs_20.svg 404 (File not found)
Image (async)
(anonymous) @ d3plus-hierarchy.v0.9.full.min.js:7
cp @ d3plus-hierarchy.v0.9.full.min.js:7
yp @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:7
(anonymous) @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:7
JL @ d3plus-hierarchy.v0.9.full.min.js:31
e @ d3plus-hierarchy.v0.9.full.min.js:31
e @ d3plus-hierarchy.v0.9.full.min.js:31
(anonymous) @ d3plus-hierarchy.v0.9.full.min.js:31
ZB @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:7
e @ d3plus-hierarchy.v0.9.full.min.js:31
(anonymous) @ treemap_iframe.html:3983
hs_21.svg:1 GET http://localhost:8000/images/icons/hs/hs_2.svg,../images/icons/hs/hs_21.svg 404 (File not found)

If I check the network output, it shows that its' initiator is text/html instead of svg+xml.

**Comment by davelandry** [comment]
@mhealey I've placed your Group 1 and Group 2 example data points into the example I made, and everything looks like it works to me. The legend shows 2 separate blocks with matching colors and labels to the parents in the data: https://jsfiddle.net/3zx9cgb4/

The other error you posted looks related to the relative path of the images. When linking to web images, it is best practice to link from "root", meaning starting with a forward slash `/` at the top-most directory. I think to fix your images you may only need to replace `"../` at the start of each string with just `"/`.
